// @flow

export default {
  GET_MOVIE: 'GET_MOVIE',
  GET_MOVIE_REQUEST: 'GET_MOVIE_REQUEST',
  GET_MOVIE_SUCCESS: 'GET_MOVIE_SUCCESS',
  GET_MOVIE_FAILURE: 'GET_MOVIE_FAILURE',

  GET_MOVIE_CAST: 'GET_MOVIE_CAST',
  GET_MOVIE_CAST_REQUEST: 'GET_MOVIE_CAST_REQUEST',
  GET_MOVIE_CAST_SUCCESS: 'GET_MOVIE_CAST_SUCCESS',
  GET_MOVIE_CAST_FAILURE: 'GET_MOVIE_CAST_FAILURE',

  DISCOVER_MOVIES: 'DISCOVER_MOVIES',
  DISCOVER_MOVIES_REQUEST: 'DISCOVER_MOVIES_REQUEST',
  DISCOVER_MOVIES_SUCCESS: 'DISCOVER_MOVIES_SUCCESS',
  DISCOVER_MOVIES_FAILURE: 'DISCOVER_MOVIES_FAILURE',

  BOOKMART_MOVIE: 'BOOKMART_MOVIE',
  BOOKMART_MOVIE_REQUEST: 'BOOKMART_MOVIE_REQUEST',
  BOOKMART_MOVIE_SUCCESS: 'BOOKMART_MOVIE_SUCCESS',
  BOOKMART_MOVIE_FAILURE: 'BOOKMART_MOVIE_FAILURE'
}
