// @flow

export default {
  GET_MOVIE: 'GET_MOVIE',
  GET_MOVIE_REQUEST: 'GET_MOVIE_REQUEST',
  GET_MOVIE_SUCCESS: 'GET_MOVIE_SUCCESS',
  GET_MOVIE_FAILURE: 'GET_MOVIE_FAILURE',

  GET_MOVIE_CAST: 'GET_MOVIE_CAST',
  GET_MOVIE_CAST_REQUEST: 'GET_MOVIE_CAST_REQUEST',
  GET_MOVIE_CAST_SUCCESS: 'GET_MOVIE_CAST_SUCCESS',
  GET_MOVIE_CAST_FAILURE: 'GET_MOVIE_CAST_FAILURE',

  BOOKMART_MOVIE: 'BOOKMART_MOVIE',
  BOOKMART_MOVIE_REQUEST: 'BOOKMART_MOVIE_REQUEST',
  BOOKMART_MOVIE_SUCCESS: 'BOOKMART_MOVIE_SUCCESS',
  BOOKMART_MOVIE_FAILURE: 'BOOKMART_MOVIE_FAILURE'
}
